version: '3.8'

services:
  backend:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
    - ./backend:/backend
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
      - 443:443
    volumes:
    - ./backend:/backend
    depends_on:
      - backend
      - db

volumes:
  postgres_data:
  static_volume: